import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "../redux/Provider";
import store from "../redux/Store";
import Socket from "../socket/socket";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hafiz Muhammad Faaiz Azeem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
 
        <Providers store={store}>
          <Socket>{children}</Socket>
        </Providers>
      </body>
    </html>
  );
}
